default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  host: host.docker.internal
  database: wallet
  port: 3306

development:
  <<: *default

test:
  <<: *default
  database: wallet_test

production:
  <<: *default
  database: wallet_prod
